# Generated by Django 4.1.1 on 2022-09-28 13:43
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_lastverificationcode_user_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="code",
        ),
        migrations.AddField(
            model_name="lastverificationcode",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
